language: ruby
rvm:
  - 2.2.4

services:
  - postgresql

addons:
  postgresql: "9.3"

before_script:
  - cp config/database.yml.travis config/database.yml
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres