default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: amiibos_app
  password: 123456

development:
  <<: *default
  database: amiibos_app_developtment

test:
  <<: *default
  database: amiibos_app_test

production:
  <<: *default
  database: amiibos_app_production
  username: <%= ENV['AMIIBOS_APP_USERNAME'] %>
  password: <%= ENV['AMIIBOS_APP_PASSWORD'] %>
